const D: Record<string, string> = {
  'ইসলামিক কর্নার': 'Islamic corner',
  'ইসলামিক': 'Islamic',
  'নামাজের সময়, অ্যালার্ম, রোজা, কিবলা, তসবিহ, আমল, জাকাত': 'Prayer times, alarms, fasting, qibla, tasbih, amol, zakat',
  'সবার জন্য উন্মুক্ত · অফলাইনেও চলে': 'Open to everyone · works offline',
  'নামাজ ও অ্যালার্ম': 'Prayer & alarm',
  'রোজা': 'Fasting',
  'কিবলা': 'Qibla',
  'তসবিহ': 'Tasbih',
  'আমল': 'Amol',
  'জাকাত': 'Zakat',
  'ফজর': 'Fajr', 'সূর্যোদয়': 'Sunrise', 'যোহর': 'Dhuhr', 'আসর': 'Asr', 'মাগরিব': 'Maghrib',
  'এশা': 'Isha', 'সাহরি': 'Sehri', 'ইফতার': 'Iftar',
  'ঘণ্টা': 'h', 'মিনিট': 'min', 'সেকেন্ড': 'sec', 'বাকি': 'left',
  'পরের নামাজ': 'Next prayer',
  'আমার অবস্থান': 'My location',
  'সময় হয়েছে': 'It is time',
  'অ্যালার্ম মিস হয়েছে': 'Alarm missed',
  'থামান': 'Stop',
  '৫ মিনিট পরে': 'In 5 minutes',
  'ঠিক আছে': 'OK',
  'সময় মিলান': 'Adjust times',
  'আজান অ্যালার্ম': 'Adhan alarm',
  'অ্যালার্ম চালু করুন': 'Turn alarm on',
  'অ্যালার্ম বন্ধ করুন': 'Turn alarm off',
  'স্ক্রিন জাগিয়ে রাখুন (চার্জে রাখলে ভালো)': 'Keep screen awake (best while charging)',
  'আজান পরীক্ষা': 'Test adhan',
  'অফলাইনের জন্য আজান সংরক্ষণ': 'Save adhan for offline use',
  'ক্যালেন্ডারে ৩০ দিনের রিমাইন্ডার (.ics)': '30-day calendar reminders (.ics)',
  'আজানের অডিও আপলোড (অ্যাডমিন)': 'Upload adhan audio (admin)',
  'কিবলার দিক': 'Qibla direction',
  'কম্পাস চালু করুন': 'Start compass',
  'আপনি কিবলামুখী': 'You are facing the qibla',
  'ডিজিটাল তসবিহ': 'Digital tasbih',
  'রাউন্ড:': 'Rounds:',
  'মোট:': 'Total:',
  'অসীম': 'Unlimited',
  'রিসেট': 'Reset',
  'আজকের আমল': 'Today\'s deeds',
  'টানা ধারা:': 'Streak:',
  'দিন': 'days',
  'জাকাত ক্যালকুলেটর': 'Zakat calculator',
  'মোট সম্পদ': 'Total wealth',
  'দেনা বাদে': 'After debts',
  'প্রদেয় জাকাত (২.৫%)': 'Zakat due (2.5%)',
  'রমজানের সময়সূচি (আনুমানিক)': 'Ramadan timetable (approximate)',
  'সাহরি শেষ': 'Sehri ends',
  'তারিখ': 'Date',
  'আজকের হিজরি তারিখ:': 'Today\'s Hijri date:',
  'ইফতারের বাকি': 'Time to Iftar',
  'সাহরি শেষ হতে': 'Until Sehri ends',
  'পরের সাহরি শেষ হতে': 'Until next Sehri ends',
}

export default D
