const D: Record<string, string> = {
  // ডিফল্ট খাতের নাম
  'সাধারণ তহবিল': 'General fund',
  'বন্যা পুনর্বাসন': 'Flood rehabilitation',
  'শীতবস্ত্র': 'Winter clothes',
  'এতিম ও শিক্ষা': 'Orphans & education',
  'চিকিৎসা': 'Medical',

  // পেমেন্ট মাধ্যম
  'বিকাশ': 'bKash',
  'নগদ': 'Nagad',
  'রকেট': 'Rocket',
  'ব্যাংক': 'Bank',
  'হাতে হাতে': 'Cash in hand',

  // আয়-ব্যয়
  'আয়-ব্যয়': 'Finance',
  'সব বছর': 'All years',
  'সব মাস': 'All months',
  'সব খাত': 'All funds',
  'আয়': 'Income',
  'ব্যয়': 'Expense',
  'সর্বমোট উদ্বৃত্ত': 'Total balance',
  'আয়ের মধ্যে অনুদান ও মাসিক ফি দুটোই ধরা হয়েছে': 'Income includes both donations and monthly fees',
  'খাতভিত্তিক হিসাব (নির্বাচিত সময়)': 'Fund-wise accounts (selected period)',
  'খাত': 'Fund',
  'নিট': 'Net',
  'বছর': 'Year',
  'উদ্বৃত্ত': 'Balance',
  'বাৎসরিক তুলনা': 'Yearly comparison',
  '+ অনুদান যোগ': '+ Add donation',
  '+ খরচ যোগ': '+ Add expense',
  'অনুদান': 'Donation',
  'খরচ': 'Expense',
  'ফি': 'Fees',
  'শিট': 'Sheet',
  'কোনো অনুদান নেই': 'No donations',
  'কোনো খরচ নেই': 'No expenses',
  'নামহীন দাতা': 'Anonymous donor',
  'রসিদ': 'Receipt',
  'ভাউচার:': 'Voucher:',
  'ভাউচার': 'Voucher',
  'অনুমোদক:': 'Approved by:',
  'অনুমোদক': 'Approved by',
  'রশিদ/প্রুফ দেখুন': 'View receipt/proof',
  'সকল সদস্য (ফি:': 'All members (fee:',
  'সাল)': 'year)',
  'নাম': 'Name',
  'সাল। মাসের ঘরে ট্যাপ করলে পরিশোধ হবে, আবার ট্যাপ করলে বাতিল। প্রতি মাসের ফি:':
    'Tap a month to mark it paid; tap again to undo. Monthly fee:',
  'মাসিক ফির পরিমাণ': 'Monthly fee amount',
  'সেভ': 'Save',
  'গুগল শিটের লিংক (শেয়ার: "লিংক আছে এমন যে কেউ - ভিউয়ার")':
    'Google Sheet link (share: "Anyone with the link - Viewer")',
  'নতুন ট্যাবে খুলুন': 'Open in new tab',
  'এখনও কোনো শিট যুক্ত করা হয়নি': 'No sheet has been linked yet',
  'অনুদান সম্পাদনা': 'Edit donation',
  'নতুন অনুদান': 'New donation',
  'সদস্য নন (নাম লিখুন)': 'Not a member (type name)',
  'দাতার নাম': 'Donor name',
  'টাকার পরিমাণ *': 'Amount *',
  'খাত বাছাই করুন *': 'Select fund *',
  'ট্রানজেকশন আইডি (ঐচ্ছিক)': 'Transaction ID (optional)',
  'টাকার পরিমাণ ও খাত বাছাই করুন': 'Enter the amount and select a fund',
  'খরচ সম্পাদনা': 'Edit expense',
  'নতুন খরচের ভাউচার': 'New expense voucher',
  'খরচের ধরন (যেমন: খাদ্য সামগ্রী)': 'Expense type (e.g. food items)',
  'বিবরণ *': 'Description *',
  'বিবরণ': 'Description',
  'রশিদ/মেমোর ছবির লিংক (ঐচ্ছিক)': 'Receipt/memo photo link (optional)',
  'টাকা, খাত ও বিবরণ দিন': 'Enter amount, fund and description',

  // খাত খতিয়ান
  'খাতভিত্তিক স্বচ্ছতা ও ফান্ড লেজার': 'Fund-wise transparency & fund ledger',
  'আলাদা আলাদা খাত অনুযায়ী আয়-ব্যয়ের হিসাব': 'Income-expense accounts by separate funds',
  'প্রতিটি তহবিলের আলাদা ব্যালেন্স ও খরচের হিসাব, সময়সহ।':
    'Separate balance and expense accounts for each fund, with timestamps.',
  '+ নতুন খাত তৈরি করুন': '+ Create new fund',
  'এই খাতে লেনদেন আছে, তাই মোছা যাবে না। চাইলে নাম বা বিবরণ সম্পাদনা করুন।':
    'This fund has transactions, so it cannot be deleted. You can edit its name or description instead.',
  'খাতটি মুছে ফেলবেন?': 'Delete this fund?',
  'মোছা যায়নি:': 'Could not delete:',
  'মোট সংগৃহীত:': 'Total collected:',
  'মোট খরচ:': 'Total expense:',
  'খাত উদ্বৃত্ত (Balance):': 'Fund balance:',
  'খরচের অনুপাত:': 'Expense ratio:',
  'খাত তৈরি:': 'Fund created:',
  'সর্বশেষ লেনদেন:': 'Last transaction:',
  'এখনও কোনো লেনদেন নেই': 'No transactions yet',
  'সকল খাতের যৌথ আর্থিক বিবরণ': 'Combined financial statement of all funds',
  'টি অনুদান/ফি জমা এবং': 'donation/fee deposits and',
  'টি খরচের ভাউচার': 'expense vouchers',
  'কোনো লেনদেন নেই': 'No transactions',
  'খাত সম্পাদনা': 'Edit fund',
  'নতুন খাত': 'New fund',
  'খাতের নাম *': 'Fund name *',
  'কোড (যেমন: SEC-FLOOD, খালি রাখলে নিজে হবে)': 'Code (e.g. SEC-FLOOD, auto if left empty)',
  'বাজেট (ঐচ্ছিক)': 'Budget (optional)',
  'খাতের নাম দিন': 'Enter fund name',

  // প্রকল্প
  'বন্যা ও ত্রাণ': 'Flood & relief',
  'শিক্ষা ও এতিম': 'Education & orphans',
  'জরুরি চিকিৎসা': 'Emergency medical',
  'অন্যান্য': 'Others',
  'সক্রিয় প্রকল্প ও অনুদানের খাত': 'Active projects & donation funds',
  'আর্তমানবতার পাশে দাঁড়ান আপনার সামর্থ্য অনুযায়ী': 'Stand beside suffering humanity as per your ability',
  'আপনার দান সরাসরি বিপন্ন মানুষের খাদ্য, আশ্রয় ও চিকিৎসায় ব্যয় হয়। প্রতিটি প্রকল্পের আপডেট সময়সহ এখানে প্রকাশিত হয়।':
    'Your donation goes directly to food, shelter and treatment for people in distress. Updates for every project are published here with timestamps.',
  '+ নতুন প্রকল্প': '+ New project',
  'প্রকল্প বা এলাকা খুঁজুন...': 'Search project or area...',
  'সকল প্রকল্প': 'All projects',
  'এখনও কোনো প্রকল্প নেই': 'No projects yet',
  'বাংলাদেশ': 'Bangladesh',
  'সম্পন্ন': 'Completed',
  'সংগৃহীত:': 'Collected:',
  'লক্ষ্যমাত্রা:': 'Goal:',
  'অগ্রগতি:': 'Progress:',
  '% সম্পন্ন · খরচ:': '% complete · Spent:',
  'পরিবার উপকৃত': 'families benefited',
  'প্রকাশ:': 'Published:',
  'সর্বশেষ আপডেট:': 'Last update:',
  'অনুদানের হাত বাড়ান': 'Extend a helping hand',
  'আপডেট লুকান': 'Hide updates',
  'আপডেট দেখুন (': 'View updates (',
  'টাকা পাঠিয়ে কোষাধ্যক্ষকে জানালে আপনার অনুদানের রসিদ ও এন্ট্রি আয়-ব্যয়ে সময়সহ দেখা যাবে।':
    'After sending money, inform the treasurer and your donation receipt and entry will appear in Finance with the time.',
  'বন্ধ করুন': 'Close',
  'লিংক কপি হয়েছে': 'Link copied',
  'আপডেটের লেখা দিন': 'Enter update text',
  'নতুন আপডেট লিখুন...': 'Write a new update...',
  'ছবি': 'Photo',
  'আপডেট দিন': 'Post update',
  'এখনও কোনো আপডেট নেই': 'No updates yet',
  'আপডেটটি মুছবেন?': 'Delete this update?',
  'প্রকল্পটি ও এর সব আপডেট মুছে ফেলবেন?': 'Delete this project and all its updates?',
  'প্রকল্প সম্পাদনা': 'Edit project',
  'নতুন প্রকল্প': 'New project',
  'প্রকল্পের নাম *': 'Project name *',
  'এলাকা (যেমন: ফেনী, নোয়াখালী)': 'Area (e.g. Feni, Noakhali)',
  'কভার ছবি বাছাই': 'Choose cover photo',
  'লক্ষ্যমাত্রা (টাকা)': 'Goal (BDT)',
  'সংযুক্ত খাত (সংগৃহীত টাকা যেখান থেকে আসবে)': 'Linked fund (where the collected money comes from)',
  'উপকৃত পরিবার (সংখ্যা)': 'Families benefited (number)',
  'চলমান': 'Ongoing',
  'প্রকল্পের নাম দিন': 'Enter project name',

  // চ্যাট
  'চ্যাট ব্যবহার করতে সদস্য হিসেবে লগইন করুন।': 'Log in as a member to use chat.',
  'অ্যাডমিন আপনাকে সদস্য হিসেবে যুক্ত করলে চ্যাট চালু হবে।': 'Chat will be enabled once the admin adds you as a member.',
  'কমিউনিটি রুম': 'Community room',
  'ব্যক্তিগত': 'Private',
  'সদস্যের নাম খুঁজুন...': 'Search member name...',
  'কোনো সদস্য পাওয়া যায়নি': 'No member found',
  'এখনও কোনো বার্তা নেই': 'No messages yet',
  'বার্তা লিখুন...': 'Type a message...',
  'বার্তাটি মুছবেন?': 'Delete this message?',
  'পাঠানো যায়নি:': 'Could not send:',

  // রক্তদান
  'জরুরি রক্তদান ও ২৪/৭ লাইফলাইন': 'Emergency blood donation & 24/7 lifeline',
  'জরুরি রক্ত সন্ধান ও যোগাযোগ': 'Emergency blood search & contact',
  'মুমূর্ষু রোগীর জন্য দ্রুত রক্তদাতা খুঁজুন অথবা অ্যাম্বুলেন্স ও অক্সিজেন সেবার জন্য সরাসরি যোগাযোগ করুন।':
    'Quickly find blood donors for critical patients, or contact us directly for ambulance and oxygen service.',
  'রক্তদাতা হতে লগইন করুন': 'Log in to become a blood donor',
  'আপনি রক্তদাতা তালিকায় আছেন (': 'You are in the blood donor list (',
  'প্রস্তুত (ব্যস্ত করুন)': 'Ready (set to busy)',
  'ব্যস্ত (প্রস্তুত করুন)': 'Busy (set to ready)',
  'তথ্য সম্পাদনা': 'Edit info',
  'রক্তদাতা হিসেবে নিবন্ধন করুন': 'Register as a blood donor',
  '২৪/৭ রক্তদান কল সেন্টার নম্বর': '24/7 blood donation call center number',
  '২৪/৭ রক্তদান কল সেন্টার': '24/7 blood donation call center',
  'যেকোনো রক্তের গ্রুপ সংগ্রহে সার্বক্ষণিক সহযোগিতা': 'Round-the-clock help to collect any blood group',
  'সরাসরি কল দিন': 'Call directly',
  'অ্যাম্বুলেন্স ও অক্সিজেন ব্যাংক নম্বর': 'Ambulance & oxygen bank number',
  'অ্যাম্বুলেন্স ও অক্সিজেন ব্যাংক': 'Ambulance & oxygen bank',
  'অক্সিজেন হেল্পলাইন': 'Oxygen helpline',
  'জাতীয় জরুরি সেবা বাংলাদেশ': 'National Emergency Service Bangladesh',
  'টোল-ফ্রি': 'Toll-free',
  'ফায়ার সার্ভিস, পুলিশ ও সরকারি অ্যাম্বুলেন্স সহায়তা': 'Fire service, police and government ambulance support',
  '৯৯৯ কল করুন': 'Call 999',
  'জরুরি নম্বর সম্পাদনা': 'Edit emergency numbers',
  'জরুরি রক্তের রিকোয়েস্ট': 'Emergency blood requests',
  '+ রিকোয়েস্ট': '+ Request',
  'এখন কোনো জরুরি রিকোয়েস্ট নেই': 'No emergency requests right now',
  'রক্ত প্রয়োজন': 'blood needed',
  'রক্তদাতা ডিরেক্টরি': 'Blood donor directory',
  'সকল গ্রুপ': 'All groups',
  'জেলা, থানা বা রক্তদাতার নাম খুঁজুন...': 'Search district, thana or donor name...',
  'মোট দাতা:': 'Total donors:',
  'প্রস্তুত:': 'Ready:',
  'কোনো রক্তদাতা পাওয়া যায়নি': 'No blood donor found',
  'রক্ত দিতে প্রস্তুত': 'Ready to donate',
  'সম্প্রতি রক্ত দিয়েছেন': 'Donated recently',
  'এখন ব্যস্ত': 'Busy now',
  'সর্বশেষ রক্তদান:': 'Last donation:',
  'তথ্য নেই': 'No data',
  'মোট রক্তদান:': 'Total donations:',
  'বার': 'times',
  'তালিকাভুক্ত:': 'Listed:',
  'কল দিন': 'Call',
  'তালিকা থেকে সরান': 'Remove from list',
  'তালিকা থেকে সরাবেন?': 'Remove from the list?',
  'রিকোয়েস্টটি মুছবেন?': 'Delete this request?',
  'সাধারণত ৩ মাস পর আবার রক্ত দেওয়া যায়। রক্তদানের আগে সুস্থতা যাচাই করুন।':
    'Blood can usually be donated again after 3 months. Check your health before donating.',
  'রক্তদাতা তথ্য': 'Donor information',
  'রক্তের গ্রুপ *': 'Blood group *',
  'ফোন নম্বর *': 'Phone number *',
  'থানা/উপজেলা': 'Thana/Upazila',
  'সর্বশেষ রক্তদানের তারিখ (থাকলে)': 'Last donation date (if any)',
  'মোট কতবার রক্ত দিয়েছেন': 'Total times donated',
  'আমি এখন রক্ত দিতে প্রস্তুত': 'I am ready to donate blood now',
  'আমি সম্মতি দিচ্ছি যে আমার নাম, এলাকা ও ফোন নম্বর সবার জন্য দৃশ্যমান হবে।':
    'I consent that my name, area and phone number will be visible to everyone.',
  'রক্তের গ্রুপ ও ফোন নম্বর দিন': 'Enter blood group and phone number',
  'তথ্য প্রকাশে সম্মতি দিতে টিক দিন': 'Tick to give consent for publishing the information',
  'হাসপাতালের নাম': 'Hospital name',
  'যোগাযোগের নম্বর *': 'Contact number *',
  'অতিরিক্ত তথ্য': 'Additional info',
  'রক্তের গ্রুপ ও যোগাযোগের নম্বর দিন': 'Enter blood group and contact number',
}

export default D
