const D: Record<string, string> = {
  'আবেদন করুন': 'Apply',
  'আমরা পাশে আছি': 'We are by your side',
  'নিচের যেকোনো আবেদন সদস্য না হয়েও করতে পারবেন।': 'You can submit any request below without being a member.',
  'রক্তের জন্য আবেদন': 'Request blood',
  'সাহায্যের আবেদন': 'Request help',
  'যোগাযোগ': 'Contact',
  'জরুরি রক্ত দরকার? তথ্য দিন': 'Need blood urgently? Give the details',
  'চিকিৎসা, শিক্ষা, খাদ্য ইত্যাদি': 'Medical, education, food etc.',
  'আমাদের পরিবারে যুক্ত হোন': 'Join our family',
  'প্রশ্ন বা পরামর্শ পাঠান': 'Send a question or suggestion',
  'জরুরি হটলাইন:': 'Emergency hotline:',
  'এখন যাদের রক্ত দরকার': 'Who needs blood now',
  'রক্ত দিতে চাইলে সদস্য হয়ে রক্তদাতা তালিকায় নাম লিখুন।': 'To donate blood, become a member and register as a donor.',
  'কেন আমরা': 'Why us',
  'যে দান আপনি নিজে যাচাই করতে পারবেন': 'Giving you can verify yourself',
  'স্বচ্ছ হিসাব': 'Transparent accounts',
  'যাচাইকৃত কাজ': 'Verified work',
  'রসিদসহ অনুদান': 'Donations with receipts',
  'অগ্রগতি সরাসরি': 'Live progress',
  'রক্তদাতা নেটওয়ার্ক': 'Blood donor network',
  'বিপদে পাশে': 'Beside you in need',
  'সহজ পদ্ধতি': 'Simple process',
  'আপনার দান কীভাবে পৌঁছায়': 'How your gift travels',
  'তহবিল বাছুন': 'Choose a fund',
  'পাঠিয়ে জমা দিন': 'Send and submit',
  'হিসাবে দেখুন': 'See it in the accounts',
  'চলমান প্রকল্প': 'Active projects',
  'যাদের অপেক্ষায় প্রকল্পগুলো': 'The people our projects wait for',
  'প্রতিটি প্রকল্পের অগ্রগতি নিয়মিত হালনাগাদ হয়।': 'Every project is updated regularly.',
  'সংগৃহীত': 'raised',
  'লক্ষ্য': 'goal',
  'এই প্রকল্পে দান করুন': 'Donate to this project',
  'আমাদের মানুষ': 'Our people',
  'প্রতিটি সেবার পেছনের হাত': 'The hands behind every service',
  'মাঠ থেকে': 'From the field',
  'যাচাইকৃত কাজের গল্প': 'Verified work stories',
  'কেউ না কেউ আপনার উদারতার অপেক্ষায় আছে।': 'Someone is waiting for your generosity.',
  'যত ছোটই হোক, প্রতিটি দান আজ একটা সত্যিকারের গল্প এগিয়ে নেয়।': 'However small, every gift moves a real story forward today.',
  'এখনই দান করুন': 'Donate now',
  'ঘোষণা': 'Announcements',
  'আপনার কথা শুনতে চাই': 'We\'d love to hear from you',
  'ফোন করুন': 'Call us',
  'বার্তা পাঠান': 'Send message',
  'দ্রুত লিংক': 'Quick links',
  'অংশ নিন': 'Get involved',
  'প্রকল্পসমূহ': 'Projects',
  'রক্তের আবেদন': 'Blood request',
  'আমার অ্যাকাউন্ট': 'My account',
  'মোট সংগৃহীত': 'Total raised',
  'যাচাইকৃত': 'Verified',
  'প্রতিটি কাজের প্রমাণ': 'Proof of every activity',
  'আমাদের সাথে আছেন': 'are with us',
  'আপনার নাম লিখুন': 'Enter your name',
  'রোগীর তথ্য দিন। আমাদের দায়িত্বশীলরা যাচাই করে রক্তদাতাদের জানাবেন।': 'Give the patient details. Our responsible members will verify and inform blood donors.',
  'আপনার প্রয়োজনের কথা লিখুন। যাচাইয়ের পর আমরা যোগাযোগ করব।': 'Write about your need. We will contact you after verification.',
  'প্রশ্ন, পরামর্শ বা অন্য যেকোনো কথা লিখুন।': 'Write any question, suggestion or message.',
  'আবেদন জমা হয়েছে': 'Request submitted',
  'এখনই জরুরি': 'Urgent right now',
  'আবেদন জমা দিন': 'Submit request',
  'আপনার তথ্য শুধু আমাদের দায়িত্বশীলরা দেখবেন। ভুয়া আবেদন দেবেন না।': 'Only our responsible members will see your information. Please do not submit false requests.',
  'আবেদন ইনবক্স': 'Request inbox',
  'যাচাই করে প্রকাশ': 'Verify & publish',
  'গ্রহণ': 'Accept',
  'প্রত্যাখ্যান': 'Reject',
  'নোট': 'Note',
  'কোনো আবেদন নেই': 'No requests',
}

export default D
