const D: Record<string, string> = {
  // বিভাগ
  'ঢাকা বিভাগ': 'Dhaka Division', 'চট্টগ্রাম বিভাগ': 'Chattogram Division',
  'রাজশাহী বিভাগ': 'Rajshahi Division', 'খুলনা বিভাগ': 'Khulna Division',
  'বরিশাল বিভাগ': 'Barishal Division', 'সিলেট বিভাগ': 'Sylhet Division',
  'রংপুর বিভাগ': 'Rangpur Division', 'ময়মনসিংহ বিভাগ': 'Mymensingh Division',

  // ঢাকা
  'ঢাকা': 'Dhaka', 'গাজীপুর': 'Gazipur', 'নারায়ণগঞ্জ': 'Narayanganj', 'মুন্সিগঞ্জ': 'Munshiganj',
  'নরসিংদী': 'Narsingdi', 'মানিকগঞ্জ': 'Manikganj', 'টাঙ্গাইল': 'Tangail', 'কিশোরগঞ্জ': 'Kishoreganj',
  'ফরিদপুর': 'Faridpur', 'গোপালগঞ্জ': 'Gopalganj', 'মাদারীপুর': 'Madaripur', 'রাজবাড়ী': 'Rajbari',
  'শরীয়তপুর': 'Shariatpur',
  // চট্টগ্রাম
  'চট্টগ্রাম': 'Chattogram', 'কক্সবাজার': "Cox's Bazar", 'কুমিল্লা': 'Cumilla',
  'ব্রাহ্মণবাড়িয়া': 'Brahmanbaria', 'চাঁদপুর': 'Chandpur', 'লক্ষ্মীপুর': 'Lakshmipur',
  'নোয়াখালী': 'Noakhali', 'ফেনী': 'Feni', 'খাগড়াছড়ি': 'Khagrachhari', 'রাঙামাটি': 'Rangamati',
  'বান্দরবান': 'Bandarban',
  // রাজশাহী
  'রাজশাহী': 'Rajshahi', 'বগুড়া': 'Bogura', 'জয়পুরহাট': 'Joypurhat', 'নওগাঁ': 'Naogaon',
  'নাটোর': 'Natore', 'চাঁপাইনবাবগঞ্জ': 'Chapainawabganj', 'পাবনা': 'Pabna', 'সিরাজগঞ্জ': 'Sirajganj',
  // খুলনা
  'খুলনা': 'Khulna', 'বাগেরহাট': 'Bagerhat', 'সাতক্ষীরা': 'Satkhira', 'যশোর': 'Jashore',
  'নড়াইল': 'Narail', 'মাগুরা': 'Magura', 'ঝিনাইদহ': 'Jhenaidah', 'কুষ্টিয়া': 'Kushtia',
  'চুয়াডাঙ্গা': 'Chuadanga', 'মেহেরপুর': 'Meherpur',
  // বরিশাল
  'বরিশাল': 'Barishal', 'ভোলা': 'Bhola', 'পটুয়াখালী': 'Patuakhali', 'পিরোজপুর': 'Pirojpur',
  'ঝালকাঠি': 'Jhalokati', 'বরগুনা': 'Barguna',
  // সিলেট
  'সিলেট': 'Sylhet', 'মৌলভীবাজার': 'Moulvibazar', 'হবিগঞ্জ': 'Habiganj', 'সুনামগঞ্জ': 'Sunamganj',
  // রংপুর
  'রংপুর': 'Rangpur', 'দিনাজপুর': 'Dinajpur', 'ঠাকুরগাঁও': 'Thakurgaon', 'পঞ্চগড়': 'Panchagarh',
  'নীলফামারী': 'Nilphamari', 'লালমনিরহাট': 'Lalmonirhat', 'কুড়িগ্রাম': 'Kurigram', 'গাইবান্ধা': 'Gaibandha',
  // ময়মনসিংহ
  'ময়মনসিংহ': 'Mymensingh', 'জামালপুর': 'Jamalpur', 'নেত্রকোনা': 'Netrokona', 'শেরপুর': 'Sherpur',

  // দুর্যোগ ও ক্যাটাগরি
  'বন্যা': 'Flood', 'ঘূর্ণিঝড়': 'Cyclone', 'অগ্নিকাণ্ড': 'Fire', 'ভূমিধস': 'Landslide',
  'নদীভাঙন': 'River erosion', 'শিক্ষা': 'Education', 'স্বাস্থ্য সেবা': 'Health service',
  'ত্রাণ ও পুনর্বাসন': 'Relief & rehabilitation',

  // সাহায্য ম্যাপ
  'ফিল্ড অ্যাক্টিভিটি ও ত্রাণ ট্র্যাকিং': 'Field activity & relief tracking',
  'সাহায্য প্রদান লোকেশন ট্র্যাকিং ও ইন্টারেক্টিভ ম্যাপ': 'Relief location tracking & interactive map',
  'বাংলাদেশের কোন কোন জেলায় ত্রাণ ও পুনর্বাসন পৌঁছেছে তার তথ্য, ছবি ও ভিডিও প্রমাণসহ দেখুন।':
    'See in which districts of Bangladesh relief and rehabilitation has reached, with photo and video proof.',
  '+ নতুন লোকেশন রেকর্ড যুক্ত করুন': '+ Add new location record',
  'সমগ্র বাংলাদেশ': 'Whole Bangladesh',
  'লোকেশন': 'Locations',
  'উপকৃত পরিবার': 'Families benefited',
  'মোট সহায়তা': 'Total aid',
  'বাংলাদেশ ত্রাণ বিতরণ জোন ও লোকেশন পিন': 'Bangladesh relief distribution zones & location pins',
  'আনুমানিক রেখাচিত্র · পিনে ট্যাপ করে বিস্তারিত দেখুন': 'Approximate sketch · tap a pin for details',
  'এখনও কোনো লোকেশন রেকর্ড নেই': 'No location records yet',
  'টি পরিবার': 'families',
  'টি': '',
  'সাহায্যপ্রাপ্ত পরিবার': 'Families helped',
  'মোট সহায়তার পরিমাণ': 'Total aid amount',
  'ত্রাণ কার্যক্রমের সারসংক্ষেপ:': 'Relief activity summary:',
  'বিতরণকৃত সামগ্রী:': 'Distributed items:',
  'সমন্বয়ক:': 'Coordinator:',
  'বিতরণের তারিখ:': 'Distribution date:',
  'রেকর্ড প্রকাশ:': 'Record published:',
  'সম্পাদিত:': 'Edited:',
  'মাঠপর্যায়ের ভিডিও প্রতিবেদন দেখুন': 'Watch the field video report',
  'প্রমাণ/ডকুমেন্ট দেখুন': 'View proof/document',
  'রেকর্ডটি মুছে ফেলবেন?': 'Delete this record?',
  'রেকর্ড সম্পাদনা': 'Edit record',
  'নতুন লোকেশন রেকর্ড': 'New location record',
  'জেলা বাছাই করুন *': 'Select district *',
  'শিরোনাম * (যেমন: ফুলগাজী ও পরশুরাম)': 'Title * (e.g. Fulgazi & Parshuram)',
  'নির্দিষ্ট এলাকা (ঐচ্ছিক)': 'Specific area (optional)',
  'সাহায্যপ্রাপ্ত পরিবার (সংখ্যা)': 'Families helped (number)',
  'মোট সহায়তার পরিমাণ (টাকা)': 'Total aid amount (BDT)',
  'ত্রাণ কার্যক্রমের সারসংক্ষেপ': 'Relief activity summary',
  'বিতরণকৃত সামগ্রী': 'Distributed items',
  'সমন্বয়কের নাম': 'Coordinator name',
  'বিতরণের তারিখ': 'Distribution date',
  'কভার ছবি': 'Cover photo',
  'ভিডিওর লিংক (YouTube ইত্যাদি)': 'Video link (YouTube etc.)',
  'প্রমাণ/ডকুমেন্টের লিংক': 'Proof/document link',
  'শিরোনাম ও জেলা বাছাই করুন': 'Enter a title and select a district',

  // কাজ ও প্রমাণ
  'ফিল্ড কার্যক্রম ও প্রমাণ দলিল': 'Field activities & proof records',
  'সাম্প্রতিক কার্যক্রম ও স্বচ্ছতার রিপোর্ট': 'Recent activities & transparency reports',
  'ছবি, ভিডিও ও অডিট ভাউচারের লিংকসহ মাঠপর্যায়ের প্রতিটি সমাজকল্যাণমূলক পদক্ষেপের পূর্ণাঙ্গ প্রতিবেদন।':
    'A complete report of every field-level social welfare step, with photos, videos and audit voucher links.',
  'রিপোর্ট জমা দিতে লগইন করুন': 'Log in to submit a report',
  '+ নতুন কাজের প্রমাণ ও পোস্ট যুক্ত করুন': '+ Add new work proof & post',
  'রিপোর্ট জমা হয়েছে। সভাপতি বা সাধারণ সম্পাদক যাচাই করলে সবার জন্য প্রকাশিত হবে।':
    'Report submitted. It will be published for everyone once the president or general secretary verifies it.',
  'সকল কার্যক্রম': 'All activities',
  'এখনও কোনো কাজের রিপোর্ট নেই': 'No work reports yet',
  'প্রতিবেদক:': 'Reporter:',
  'মোট ব্যয়িত অনুদান:': 'Total donation spent:',
  'উপকৃত:': 'Benefited:',
  'শতভাগ যাচাইকৃত': '100% verified',
  'যাচাইয়ের অপেক্ষায় (শুধু জমাদাতা ও যাচাইকারী দেখছেন)': 'Awaiting verification (visible only to the submitter and verifiers)',
  'মাঠপর্যায়ের প্রমাণ ছবি #': 'Field proof photo #',
  'টি মন্তব্য': 'comments',
  'এখনও কোনো মন্তব্য নেই': 'No comments yet',
  'মন্তব্য লিখুন...': 'Write a comment...',
  'মন্তব্য করতে লগইন করুন': 'Log in to comment',
  'মন্তব্যটি মুছবেন?': 'Delete this comment?',
  'ভিডিও রিপোর্ট দেখুন': 'Watch video report',
  'অডিট ভাউচার ডকুমেন্ট': 'Audit voucher document',
  'স্বচ্ছতা আইডি:': 'Transparency ID:',
  'যাচাই করুন': 'Verify',
  'যাচাই প্রত্যাহার': 'Withdraw verification',
  'রিপোর্টটি মুছে ফেলবেন?': 'Delete this report?',
  'রিপোর্ট সম্পাদনা': 'Edit report',
  'নতুন কাজের রিপোর্ট': 'New work report',
  'জায়গা (যেমন: ফুলগাজী, ফেনী)': 'Place (e.g. Fulgazi, Feni)',
  'কাজের তারিখ ও সময়': 'Date & time of work',
  'কাজের বিবরণ': 'Work description',
  'মোট ব্যয়িত অনুদান (টাকা)': 'Total donation spent (BDT)',
  'উপকৃত মানুষ/পরিবার (সংখ্যা)': 'People/families benefited (number)',
  'প্রমাণ ছবি যোগ (সর্বোচ্চ ৪টি)': 'Add proof photos (max 4)',
  'ভিডিও রিপোর্টের লিংক (ঐচ্ছিক)': 'Video report link (optional)',
  'অডিট ভাউচার/ডকুমেন্টের লিংক (ঐচ্ছিক)': 'Audit voucher/document link (optional)',
  'জমা দিলে এটি "যাচাইয়ের অপেক্ষায়" থাকবে এবং সভাপতি বা সাধারণ সম্পাদক যাচাই করলে সবার জন্য প্রকাশিত হবে।':
    'Once submitted it will stay "awaiting verification" and be published for everyone after the president or general secretary verifies it.',
  'জমা দিন': 'Submit',

  // স্বেচ্ছাসেবক ও দায়িত্ব
  'স্বেচ্ছাসেবক, দায়িত্ব ও হাজিরা': 'Volunteers, duties & attendance',
  'স্বেচ্ছাসেবক ও দায়িত্ব বণ্টন': 'Volunteers & duty assignment',
  'প্রতিটি পদের দায়িত্ব, কাজের অগ্রগতি, মিটিং ও ফিল্ড ট্রিপের উপস্থিতি এক জায়গায়।':
    'Duties of every role, work progress, and meeting & field trip attendance in one place.',
  'আপনার পদ': 'Your role',
  'পদে অর্পিত দায়িত্বসমূহ:': 'Responsibilities of the role:',
  'অ্যাডমিন প্যানেল': 'Admin panel',
  'রিপোর্ট যাচাই': 'Verify reports',
  'প্রকল্প': 'Projects',
  'সাহায্য ম্যাপ': 'Relief map',
  'নোটিশ প্রকাশ': 'Publish notice',
  'হাজিরা খাতা': 'Attendance book',
  'ইভেন্ট ম্যানেজমেন্ট': 'Event management',
  'খাত খতিয়ান': 'Fund ledger',
  'রক্তদান SOS': 'Blood donation SOS',
  'নোটিশ ও গ্যালারি': 'Notices & gallery',
  'কাজের প্রমাণ': 'Work proof',
  'রিপোর্ট জমা': 'Submit report',
  'রক্তদাতা নিবন্ধন': 'Blood donor registration',
  'দায়িত্ব': 'Duties',
  'হাজিরা': 'Attendance',
  'সদস্য তালিকা': 'Member list',
  'দায়িত্ব ও কাজের অগ্রগতি দেখতে লগইন করুন।': 'Log in to see duties and work progress.',
  'করণীয়': 'To do',
  'কেউ নয়': 'Nobody',
  'শেষ তারিখ:': 'Due date:',
  'মেয়াদ পেরিয়েছে': 'overdue',
  'বণ্টন:': 'Assigned:',
  'আপডেট:': 'Updated:',
  'সম্পন্ন:': 'Completed:',
  '+ দায়িত্ব বণ্টন করুন': '+ Assign duty',
  'আমার দায়িত্ব': 'My duties',
  'আপনাকে এখনও কোনো দায়িত্ব দেওয়া হয়নি': 'You have not been assigned any duty yet',
  'সকল দায়িত্ব': 'All duties',
  'কোনো দায়িত্ব নেই': 'No duties',
  'দায়িত্বটি মুছে ফেলবেন?': 'Delete this duty?',
  'দায়িত্ব সম্পাদনা': 'Edit duty',
  'নতুন দায়িত্ব': 'New duty',
  'দায়িত্বের শিরোনাম *': 'Duty title *',
  'কাকে দেবেন? *': 'Assign to whom? *',
  'শেষ তারিখ (ঐচ্ছিক)': 'Due date (optional)',
  'শিরোনাম দিন ও সদস্য বাছাই করুন': 'Enter a title and select a member',
  'আপনার উপস্থিতি:': 'Your attendance:',
  'টি ইভেন্ট': 'events',
  '+ নতুন ইভেন্ট (সভা/ফিল্ড ট্রিপ/অনুষ্ঠান)': '+ New event (meeting/field trip/program)',
  'এখনও কোনো ইভেন্ট নেই': 'No events yet',
  'সভা': 'Meeting',
  'ফিল্ড ট্রিপ': 'Field trip',
  'টুর্নামেন্ট': 'Tournament',
  'সাংস্কৃতিক অনুষ্ঠান': 'Cultural program',
  'আসন্ন': 'Upcoming',
  'উপস্থিত:': 'Present:',
  'অনুপস্থিত:': 'Absent:',
  'উপস্থিত': 'Present',
  'অনুপস্থিত': 'Absent',
  'হাজিরা নিন': 'Take attendance',
  'উপস্থিতি দেখুন': 'View attendance',
  'সবাই উপস্থিত': 'Mark all present',
  'ইভেন্ট ও এর হাজিরা মুছে ফেলবেন?': 'Delete the event and its attendance?',
  'ইভেন্ট সম্পাদনা': 'Edit event',
  'নতুন ইভেন্ট': 'New event',
  'ইভেন্টের নাম *': 'Event name *',
  'তারিখ ও সময়': 'Date & time',
  'স্থান': 'Venue',
  'ইভেন্টের নাম দিন': 'Enter event name',
  'নাম, জেলা বা আইডি খুঁজুন...': 'Search name, district or ID...',
  'সবাই': 'Everyone',
  'স্বেচ্ছাসেবক/সদস্য': 'Volunteers/Members',
  'মোট:': 'Total:',
  'কাউকে পাওয়া যায়নি': 'No one found',

  // পদের দায়িত্ব
  'সদস্য যুক্ত করা, পদবী বণ্টন ও অ্যাডমিন ক্ষমতা নিয়ন্ত্রণ': 'Add members, assign roles and control admin powers',
  'ফাউন্ডেশনের নাম, লোগো, থিম ও যোগাযোগের তথ্য হালনাগাদ রাখা': 'Keep the foundation name, logo, theme and contact info updated',
  'আর্থিক ও কার্যক্রমের তথ্যের স্বচ্ছতা নিশ্চিত করা': 'Ensure transparency of financial and activity data',
  'ফাউন্ডেশনের সামাজিক নীতি নির্ধারণ ও কার্যক্রমের দিকনির্দেশনা প্রদান': 'Set social policy and give direction for activities',
  'জাতীয় ও আন্তর্জাতিক সংস্থার সাথে যোগাযোগ ও চুক্তি সম্পাদন': 'Liaise and sign agreements with national and international organizations',
  'বার্ষিক বাজেট অনুমোদন ও বিশেষ জরুরি ত্রাণ তহবিলের চূড়ান্ত তদারকি': 'Approve the annual budget and oversee the special emergency relief fund',
  'দৈনন্দিন সাংগঠনিক কার্যক্রম পরিচালনা ও সদস্যদের মধ্যে সমন্বয়': 'Run daily organizational work and coordinate among members',
  'মিটিং ও ফিল্ড ট্রিপের আয়োজন এবং ডিজিটাল হাজিরা রক্ষণ': 'Organize meetings and field trips and keep digital attendance',
  'ফিল্ড রিপোর্ট যাচাই ও দায়িত্ব বণ্টন': 'Verify field reports and assign duties',
  'অনুদান ও মাসিক ফি গ্রহণ এবং রসিদ প্রদান': 'Receive donations and monthly fees and issue receipts',
  'খরচের ভাউচার এন্ট্রি ও ক্যাশ ব্যালেন্স সংরক্ষণ': 'Enter expense vouchers and maintain the cash balance',
  'আর্থিক অডিটে সহযোগিতা ও খাতভিত্তিক হিসাব হালনাগাদ': 'Support financial audits and keep fund-wise accounts updated',
  'জরুরি রক্তের রিকোয়েস্ট তৈরি ও প্রচার': 'Create and promote emergency blood requests',
  'রক্তদাতা তালিকা হালনাগাদ ও যাচাই': 'Update and verify the blood donor list',
  'স্বাস্থ্য ক্যাম্প ও সচেতনতামূলক কর্মসূচি সমন্বয়': 'Coordinate health camps and awareness programs',
  'যুব কল্যাণ টুর্নামেন্ট ও সাংস্কৃতিক ইভেন্ট আয়োজন': 'Organize youth welfare tournaments and cultural events',
  'অংশগ্রহণকারী ও স্বেচ্ছাসেবকদের সমন্বয়': 'Coordinate participants and volunteers',
  'ছবি, ভিডিও গ্যালারি ও প্রেস রিলিজ প্রকাশ': 'Publish photo & video gallery and press releases',
  'নোটিশ বোর্ড হালনাগাদ ও সামাজিক যোগাযোগমাধ্যম পরিচালনা': 'Update the notice board and manage social media',
  'মাঠপর্যায়ের কাজের রিপোর্ট জমা দেওয়া': 'Submit field work reports',
  'নিয়মিত মাসিক ফি পরিশোধ করা': 'Pay monthly fees regularly',
  'মিটিং ও কার্যক্রমে সক্রিয় অংশগ্রহণ': 'Participate actively in meetings and activities',

  // নোটিশ ও গ্যালারি
  'অফিসিয়াল নোটিশ বোর্ড': 'Official notice board',
  'ঘোষণা, রেজুলেশন ও প্রেস রিলিজ': 'Announcements, resolutions & press releases',
  'সংগঠনের সব অফিসিয়াল ঘোষণা এখানে সময়সহ প্রকাশিত হয়।': 'All official announcements of the organization are published here with time.',
  '+ নতুন নোটিশ': '+ New notice',
  'নোটিশ খুঁজুন...': 'Search notices...',
  'কোনো নোটিশ নেই': 'No notices',
  'জরুরি': 'Urgent',
  'নোটিশটি মুছে ফেলবেন?': 'Delete this notice?',
  'নোটিশ সম্পাদনা': 'Edit notice',
  'নতুন নোটিশ': 'New notice',
  'ছবি যোগ (ঐচ্ছিক)': 'Add photo (optional)',
  'ছবি ও ভিডিও গ্যালারি': 'Photo & video gallery',
  'কার্যক্রমের স্মৃতির ফ্রেম': 'Memory frames of our activities',
  '+ ভিডিও লিংক': '+ Video link',
  'ভিডিও': 'Video',
  'দেখুন': 'View',
  '📷 ছবি (': '📷 Photos (',
  'ক্যাপশন বদলান': 'Change caption',
  'ক্যাপশন লিখুন:': 'Write a caption:',
  'ভিডিওর লিংক (YouTube/ফেসবুক ইত্যাদি):': 'Video link (YouTube/Facebook etc.):',
  'ভিডিওর শিরোনাম:': 'Video title:',
}

export default D
