const D: Record<string, string> = {
  'থিম ও ব্যাকগ্রাউন্ড': 'Theme & background',
  'ট্যাপ করলেই সাথে সাথে বদলায়। আপনার পছন্দ শুধু এই ফোনে মনে থাকে।': 'Changes apply instantly. Your choice is remembered on this phone only.',
  'ব্যাকগ্রাউন্ড': 'Background',
  'কণা-জাল': 'Particle network',
  'নড়াচড়া করা বিন্দু ও রেখা, ছুঁলে জুড়ে যায়': 'Moving dots and lines that connect when touched',
  'অরোরা': 'Aurora',
  'ধীরে বদলানো রঙিন আলো': 'Slowly shifting coloured light',
  'তারা-রাত': 'Starry night',
  'মিটমিটে তারা, চাঁদ ও উল্কা': 'Twinkling stars, moon and shooting stars',
  'ফুলের পাপড়ি': 'Flower petals',
  'ঝরে পড়া পাপড়ি': 'Falling petals',
  'বুদবুদ': 'Bubbles',
  'ভেসে ওঠা স্বচ্ছ বুদবুদ': 'Rising translucent bubbles',
  'ঢেউ': 'Waves',
  'নিচে বয়ে চলা ঢেউ': 'Waves flowing at the bottom',
  'ইসলামি নকশা': 'Islamic pattern',
  'ধীরে সরে যাওয়া জ্যামিতিক নকশা': 'Slowly drifting geometric pattern',
  'সরল': 'Plain',
  'কোনো অ্যানিমেশন নয় (ব্যাটারি সাশ্রয়)': 'No animation (saves battery)',
  'ফন্ট': 'Font',
  'রঙ': 'Colour',
  'সবুজ': 'Green', 'নীল': 'Blue', 'বেগুনি': 'Violet', 'গোলাপি': 'Rose',
  'কমলা': 'Orange', 'টিল': 'Teal', 'মেরুন': 'Maroon',
  'কার্ডের ধরন': 'Card style',
  'সাধারণ': 'Flat',
  'কাচ (স্বচ্ছ)': 'Glass (translucent)',
  'সাইটের ডিফল্টে ফিরুন': 'Back to site default',
  'হয়েছে': 'Done',
  'অ্যাডমিন: এখনকার বাছাই (ব্যাকগ্রাউন্ড, ফন্ট, রঙ, কার্ড) যাদের নিজের কিছু বাছা নেই তাদের সবার জন্য ডিফল্ট হবে।':
    'Admin: the current choice (background, font, colour, cards) becomes the default for everyone who has not picked their own.',
  'সবার জন্য ডিফল্ট করুন': 'Make default for everyone',
  'সবার জন্য ডিফল্ট হিসেবে সেভ হয়েছে': 'Saved as the default for everyone',
}

export default D
