const D: Record<string, string> = {
  // সাধারণ
  'ব্যর্থ:': 'Failed:',
  'মুছুন': 'Delete',
  'বাতিল': 'Cancel',
  'সংরক্ষণ': 'Save',
  'সম্পাদনা': 'Edit',
  'প্রকাশ করুন': 'Publish',
  'লোড হচ্ছে...': 'Loading...',
  'মুছে ফেলবেন?': 'Delete this?',
  'অপেক্ষা করুন...': 'Please wait...',
  'সব': 'All',
  'জন': 'people',
  'আমাদের ফাউন্ডেশন': 'Our Foundation',
  'এখনও কোনো মাধ্যম যোগ করা হয়নি।': 'No payment method has been added yet.',
  'এই ফিচারটি অ্যাডমিন সাময়িকভাবে বন্ধ রেখেছেন।': 'This feature has been temporarily turned off by the admin.',

  // মাস, বার, ঋতু, বঙ্গাব্দ, হিজরি
  'জানুয়ারি': 'January', 'ফেব্রুয়ারি': 'February', 'এপ্রিল': 'April', 'জুলাই': 'July',
  'আগস্ট': 'August', 'সেপ্টেম্বর': 'September', 'অক্টোবর': 'October',
  'নভেম্বর': 'November', 'ডিসেম্বর': 'December',
  'মার্চ': 'Mar', 'মে': 'May', 'জুন': 'Jun',
  'জানু': 'Jan', 'ফেব্রু': 'Feb', 'এপ্রি': 'Apr', 'জুলা': 'Jul', 'আগ': 'Aug',
  'সেপ্টে': 'Sep', 'অক্টো': 'Oct', 'নভে': 'Nov', 'ডিসে': 'Dec',
  'রবিবার': 'Sunday', 'সোমবার': 'Monday', 'মঙ্গলবার': 'Tuesday', 'বুধবার': 'Wednesday',
  'বৃহস্পতিবার': 'Thursday', 'শুক্রবার': 'Friday', 'শনিবার': 'Saturday',
  'বৈশাখ': 'Boishakh', 'জ্যৈষ্ঠ': 'Joishtho', 'আষাঢ়': 'Asharh', 'শ্রাবণ': 'Srabon',
  'ভাদ্র': 'Bhadro', 'আশ্বিন': 'Ashwin', 'কার্তিক': 'Kartik', 'অগ্রহায়ণ': 'Ogrohayon',
  'পৌষ': 'Poush', 'মাঘ': 'Magh', 'ফাল্গুন': 'Falgun', 'চৈত্র': 'Choitro',
  'গ্রীষ্ম': 'Summer', 'বর্ষা': 'Monsoon', 'শরৎ': 'Autumn', 'হেমন্ত': 'Late autumn',
  'শীত': 'Winter', 'বসন্ত': 'Spring',
  'বঙ্গাব্দ': 'BS', 'হিজরি': 'AH',
  'মুহাররম': 'Muharram', 'মহররম': 'Muharram', 'সফর': 'Safar',
  'রবিউল আউয়াল': 'Rabi al-Awwal', 'রবিউস সানি': 'Rabi al-Thani',
  'জমাদিউল আউয়াল': 'Jumada al-Awwal', 'জমাদিউস সানি': 'Jumada al-Thani',
  'রজব': 'Rajab', 'শা’বান': 'Shaban', 'শাবান': 'Shaban', 'রমজান': 'Ramadan',
  'রমযান': 'Ramadan', 'শাওয়াল': 'Shawwal', 'জিলকদ': 'Dhu al-Qadah',
  'জ্বিলকদ': 'Dhu al-Qadah', 'জিলহজ': 'Dhu al-Hijjah', 'জ্বিলহজ্জ': 'Dhu al-Hijjah',
  'জিলহজ্জ': 'Dhu al-Hijjah', 'অপরাহ্ণ': 'PM', 'পূর্বাহ্ণ': 'AM',

  // ঘড়ি ও সোশ্যাল
  'ইংরেজি': 'English',
  'বাংলা': 'Bengali',
  'হিজরি তারিখ চাঁদ দেখার ওপর নির্ভর করে ১ দিন আগে-পিছে হতে পারে':
    'Hijri date may differ by 1 day depending on moon sighting',
  'ভার্চুয়াল মিটিং': 'Virtual meeting',
  'জুম মিটিং': 'Zoom meeting',
  'গুগল মিট': 'Google Meet',
  'আমাদের সাথে যুক্ত হোন': 'Connect with us',
  'ফেসবুক পেজ': 'Facebook page',
  'ফেসবুক গ্রুপ': 'Facebook group',
  'হোয়াটসঅ্যাপ': 'WhatsApp',
  'টেলিগ্রাম': 'Telegram',

  // হোম
  'সমাজসেবা • মানবতা • স্বেচ্ছাসেবা': 'Social service • Humanity • Volunteering',
  'মানবতার পাশে দাঁড়ানোই আমাদের অঙ্গীকার': 'Standing beside humanity is our pledge',
  'অসহায়, সুবিধাবঞ্চিত এবং বিপদগ্রস্ত মানুষের পাশে দাঁড়াতে কাজ করে। শিক্ষা, স্বাস্থ্য, খাদ্য, রক্তদান ও দুর্যোগ সহায়তায় আমাদের স্বেচ্ছাসেবকেরা একসাথে কাজ করছেন।':
    'works to stand beside helpless, underprivileged and distressed people. Our volunteers work together in education, health, food, blood donation and disaster relief.',
  'আমাদের কার্যক্রম': 'Our activities',
  'সদস্য হোন': 'Become a member',
  'সদস্য লগইন': 'Member login',
  'সক্রিয় সদস্য': 'Active members',
  'মোট অনুদান': 'Total donations',
  'সম্পন্ন কার্যক্রম': 'Completed activities',
  'সহায়তাপ্রাপ্ত পরিবার': 'Families helped',
  'অনুদানের খাত': 'Donation funds',
  'সক্রিয় প্রকল্প': 'Active projects',
  'সব প্রকল্প দেখুন →': 'View all projects →',
  'ফিল্ড কার্যক্রম': 'Field activities',
  'সাম্প্রতিক যাচাইকৃত কাজ': 'Recent verified work',
  'সব কার্যক্রম ও প্রমাণ দেখুন →': 'View all activities & proofs →',
  'আমাদের পরিচিতি': 'About us',
  'মানবসেবার মাধ্যমে একটি সুন্দর সমাজ গড়ার স্বপ্ন':
    'A dream of building a beautiful society through humanitarian service',
  'আমরা একটি স্বেচ্ছাসেবী সামাজিক সংগঠন। মানুষের মৌলিক প্রয়োজন, শিক্ষা সহায়তা, স্বাস্থ্যসেবা, রক্তদান এবং দুর্যোগকালীন সহায়তায় কাজ করছি। স্বচ্ছতা, দায়িত্ববোধ ও মানবিকতা আমাদের কাজের মূল নীতি, তাই প্রতিটি অনুদান ও খরচ "আয়-ব্যয়" ট্যাবে সবার জন্য উন্মুক্ত।':
    'We are a voluntary social organization working on basic human needs, education support, healthcare, blood donation and disaster relief. Transparency, responsibility and humanity are our core principles, so every donation and expense is open to everyone in the "Finance" tab.',
  'মানবিক সহায়তা': 'Humanitarian aid',
  'শিক্ষা সহায়তা': 'Education support',
  'রক্তদান কর্মসূচি': 'Blood donation program',
  'দুর্যোগকালীন সেবা': 'Disaster relief service',
  'আমাদের সঙ্গে যুক্ত হোন': 'Join us',
  'আমাদের উদ্যোগ': 'Our initiatives',
  'প্রধান কার্যক্রমসমূহ': 'Main activities',
  'খাদ্য ও ত্রাণ বিতরণ': 'Food & relief distribution',
  'অসহায় পরিবার ও দুর্যোগে ক্ষতিগ্রস্ত মানুষের জন্য জরুরি সহায়তা কার্যক্রম।':
    'Emergency aid programs for helpless families and people affected by disasters.',
  'শিক্ষার্থীদের পাশে': 'Beside the students',
  'সুবিধাবঞ্চিত শিক্ষার্থীদের শিক্ষা উপকরণ, বই ও বৃত্তি সহায়তা।':
    'Educational materials, books and scholarship support for underprivileged students.',
  'স্বাস্থ্যসেবা': 'Healthcare',
  'রক্তদান ও স্বাস্থ্য ক্যাম্প': 'Blood donation & health camps',
  'রক্তদাতা নেটওয়ার্ক, ফ্রি চিকিৎসা ক্যাম্প এবং সচেতনতামূলক কর্মসূচি।':
    'Blood donor network, free medical camps and awareness programs.',
  'ঘোষণা ও সংবাদ': 'Announcements & news',
  'সর্বশেষ নোটিশ': 'Latest notices',
  'নোটিশ': 'Notice',
  'সাধারণ নোটিশ': 'General notice',
  'রেজুলেশন': 'Resolution',
  'প্রেস রিলিজ': 'Press release',
  'শিরোনাম *': 'Title *',
  'শিরোনাম দিন': 'Enter a title',
  'বিস্তারিত': 'Details',
  'জরুরি নোটিশ': 'Urgent notice',
  'এখনও কোনো নোটিশ নেই': 'No notices yet',
  'সব নোটিশ দেখুন →': 'View all notices →',
  'স্মৃতির ফ্রেমে': 'In the frame of memories',
  'কার্যক্রমের গ্যালারি': 'Activity gallery',
  '+ ছবি যোগ করুন': '+ Add photo',
  'এখনও কোনো ছবি নেই': 'No photos yet',
  'সব ছবি ও ভিডিও দেখুন →': 'View all photos & videos →',
  'মানবতার কল্যাণে আমাদের সঙ্গে যুক্ত হোন': 'Join us for the welfare of humanity',
  'সদস্য, স্বেচ্ছাসেবক বা শুভাকাঙ্ক্ষী হিসেবে আপনার সামর্থ্য ও সময় দিয়ে অসহায় মানুষের মুখে হাসি ফোটাতে পাশে দাঁড়ান।':
    'As a member, volunteer or well-wisher, stand by us and bring a smile to helpless people with your capacity and time.',
  'সদস্য হওয়ার আবেদন': 'Apply for membership',
  'অনুদান পাঠানোর মাধ্যম': 'Ways to send donations',
  'মানবিকতা, স্বচ্ছতা ও দায়িত্ববোধের সঙ্গে সমাজের অসহায় মানুষের পাশে দাঁড়ানো আমাদের অঙ্গীকার।':
    'Standing beside the helpless people of society with humanity, transparency and responsibility is our pledge.',
  'সর্বস্বত্ব সংরক্ষিত': 'All rights reserved',

  // আবেদন ও লগইন
  'পূর্ণ নাম *': 'Full name *',
  'মোবাইল নম্বর *': 'Mobile number *',
  'ইমেইল (ঐচ্ছিক)': 'Email (optional)',
  'রক্তের গ্রুপ': 'Blood group',
  'জেলা': 'District',
  'কেন সদস্য হতে চান?': 'Why do you want to become a member?',
  'জমা হচ্ছে...': 'Submitting...',
  'আবেদন জমা দিন': 'Submit application',
  'নাম ও মোবাইল নম্বর দিন': 'Enter name and mobile number',
  'আবেদন জমা হয়েছে। অ্যাডমিন অনুমোদন করলে আপনি সদস্য হবেন।':
    'Application submitted. You will become a member once the admin approves.',
  'ইমেইল': 'Email',
  'পাসওয়ার্ড': 'Password',
  'লগইন': 'Login',
  'লগইন ব্যর্থ: ইমেইল বা পাসওয়ার্ড ভুল': 'Login failed: wrong email or password',

  // ড্যাশবোর্ড
  'অ্যাডমিন আপনাকে সদস্য হিসেবে যুক্ত করলে এখানে তথ্য আসবে।':
    'Information will appear here once the admin adds you as a member.',
  'লগআউট': 'Logout',
  'যোগদান:': 'Joined:',
  'প্রোফাইল ছবি দিন': 'Add profile photo',
  'মোট দান': 'Total donated',
  'ফি পরিশোধ': 'Fees paid',
  'বকেয়া': 'Due',
  'মাস': 'months',
  'মাসিক ফি খতিয়ান': 'Monthly fee ledger',
  'পেইড': 'Paid',
  'আমার দানের ইতিহাস': 'My donation history',
  'এখনও কোনো দান নেই': 'No donations yet',
  'রসিদ:': 'Receipt:',
  'ডিজিটাল আইডি কার্ড': 'Digital ID card',
  'আইডি:': 'ID:',
  'পদবী:': 'Role:',
  'রক্তের গ্রুপ:': 'Blood group:',
  'মেয়াদ:': 'Valid until:',
  'প্রিন্ট / PDF হিসেবে সেভ': 'Print / Save as PDF',
  'অ্যাডমিন': 'Admin',
  'সভাপতি': 'President',
  'সাধারণ সম্পাদক': 'General Secretary',
  'কোষাধ্যক্ষ': 'Treasurer',
  'স্বাস্থ্য ও রক্তদান সমন্বয়ক': 'Health & Blood Donation Coordinator',
  'ক্রীড়া ও সাংস্কৃতিক সম্পাদক': 'Sports & Cultural Secretary',
  'প্রচার ও প্রকাশনা সম্পাদক': 'Publicity & Publication Secretary',
  'সদস্য': 'Member',

  // পাসওয়ার্ড বদল
  'পাসওয়ার্ড পরিবর্তন': 'Change password',
  'অ্যাডমিন যে পাসওয়ার্ড দিয়েছেন, সেটা বদলে নিজের পছন্দের একটা দিন।':
    'Replace the password given by the admin with one of your own.',
  'নতুন পাসওয়ার্ড (কমপক্ষে ৮ অক্ষর)': 'New password (at least 8 characters)',
  'আবার লিখুন': 'Type again',
  'পাসওয়ার্ড বদলান': 'Change password',
  'পাসওয়ার্ড কমপক্ষে ৮ অক্ষরের হতে হবে': 'Password must be at least 8 characters',
  'দুই ঘরের পাসওয়ার্ড মিলছে না': 'The two passwords do not match',
  'পাসওয়ার্ড বদলানো হয়েছে': 'Password changed',

  // অফলাইন
  'আপনি অফলাইনে আছেন। নতুন তথ্য ও আপলোডের জন্য ইন্টারনেট লাগবে।':
    'You are offline. Internet is needed for new data and uploads.',
  'অ্যাপটি ফোনে ইনস্টল করুন': 'Install this app on your phone',
  'ইনস্টল': 'Install',
  'ইনস্টল করতে Safari-তে নিচের': 'To install, in Safari tap the',
  'শেয়ার': 'Share',
  'বাটন চেপে': 'button, then choose',
  'বাছুন।': '.',

  // অ্যাডমিন প্যানেল
  'আবেদন': 'Applications',
  'ফিচার': 'Features',
  'সেটিংস': 'Settings',
  'কোনো নতুন আবেদন নেই': 'No new applications',
  'আবেদনের সময়:': 'Applied:',
  'অনুমোদন': 'Approve',
  'সদস্যের জন্য লগইন অ্যাকাউন্ট তৈরি করুন': 'Create a login account for the member',
  'ইমেইল (লগইনের জন্য)': 'Email (for login)',
  'অনুমোদন নিশ্চিত করুন': 'Confirm approval',
  'সদস্য যুক্ত হয়েছে, কিন্তু লগইন তৈরি হয়নি:': 'Member added, but login was not created:',
  'সদস্য যুক্ত হয়েছে': 'Member added',
  'লগইন তৈরি হয়েছে:': 'Login created:',
  'ইমেইল:': 'Email:',
  'পাসওয়ার্ড:': 'Password:',
  'Supabase-এ "Confirm email" চালু আছে, তাই সদস্যকে আগে ইমেইলের লিংকে ক্লিক করতে হবে। এড়াতে ওটা বন্ধ করুন।':
    'Supabase has "Confirm email" turned on, so the member must first click the link in the email. Turn it off to avoid this.',
  'এই পাসওয়ার্ড শুধু এখন একবারই দেখা যাবে। সদস্যকে পাঠিয়ে দিন।':
    'This password is shown only once, now. Send it to the member.',
  'বার্তা কপি করুন': 'Copy message',
  'বন্ধ': 'Close',
  '(আগের পাসওয়ার্ডই চলবে)': '(the previous password will work)',
  'কপি হয়েছে': 'Copied',
  'কপি করুন:': 'Copy:',
  'মোট সদস্য': 'Total members',
  'সক্রিয় অ্যাডমিন': 'Active admins',
  'কার্যনির্বাহী পরিষদ': 'Executive committee',
  'মাঠের স্বেচ্ছাসেবক': 'Field volunteers',
  'সক্রিয়': 'Active',
  'সদস্যপদ বন্ধ করুন': 'Deactivate membership',
  'আবার চালু করুন': 'Reactivate',
  'লগইন আছে': 'Login exists',
  'লগইন তৈরি করুন': 'Create login',
  'ইমেইল ও পাসওয়ার্ড দিন': 'Enter email and password',
  'অ্যাপের ফিচার ও মডিউল অন/অফ': 'App features & module on/off',
  'লাইভ ঘড়ি ও ৩টি ক্যালেন্ডার': 'Live clock & 3 calendars',
  'ইংরেজি, বাংলা ও ইসলামিক হিজরি ক্যালেন্ডার উইজেট': 'English, Bengali and Islamic Hijri calendar widgets',
  'লাইভ চ্যাট রুম ও ১-অন-১ মেসেজিং': 'Live chat room & 1-on-1 messaging',
  'সদস্যদের যৌথ কমিউনিটি চ্যাট ও ব্যক্তিগত বার্তা': 'Community group chat and private messages for members',
  'খাতভিত্তিক পৃথক আয়-ব্যয় খতিয়ান': 'Separate income-expense ledger by fund',
  'বন্যা, শীতবস্ত্র, শিক্ষা ও চিকিৎসা খাতের আলাদা হিসাব':
    'Separate accounts for flood, winter clothes, education and medical funds',
  'ভার্চুয়াল মিটিং হাব ও সোশ্যাল লিংক': 'Virtual meeting hub & social links',
  'জুম, গুগল মিট, হোয়াটসঅ্যাপ ও ফেসবুক যোগদানের বাটন':
    'Join buttons for Zoom, Google Meet, WhatsApp and Facebook',
  'সেভ হয়েছে': 'Saved',
  'পেজ রিফ্রেশ করলে সবার কাছে বদলে যাবে।': 'Refresh the page to apply it for everyone.',
  'পেজ রিফ্রেশ হচ্ছে...': 'refreshing page...',
  'লোগো': 'Logo',
  'লোগো বাছাই করুন': 'Choose logo',
  'কভার ফটো': 'Cover photo',
  'কভার ফটো বাছাই করুন': 'Choose cover photo',
  'থিম রঙ': 'Theme color',
  'ফাউন্ডেশনের নাম': 'Foundation name',
  'স্লোগান': 'Slogan',
  'হটলাইন নম্বর': 'Hotline number',
  'ফেসবুক পেজের লিংক': 'Facebook page link',
  'ফেসবুক গ্রুপের লিংক': 'Facebook group link',
  'হোয়াটসঅ্যাপ কমিউনিটির লিংক': 'WhatsApp community link',
  'টেলিগ্রাম চ্যানেলের লিংক': 'Telegram channel link',
  'জুম মিটিং লিংক': 'Zoom meeting link',
  'গুগল মিট লিংক': 'Google Meet link',
  'ব্যাংক / বিকাশ / নগদের বিবরণ': 'Bank / bKash / Nagad details',
  'সেভ করুন': 'Save',
  'সেভ হচ্ছে...': 'Saving...',
}

export default D
