const D: Record<string, string> = {
  'শেষ হতে বাকি': 'Time left',
  'শুরু হতে বাকি': 'Starts in',
  'এখন কোনো ওয়াক্ত চলছে না': 'No prayer time is running now',
  'সূর্যাস্ত:': 'Sunset:',
  'অ্যালার্ম': 'Alarm',
  'ক্যালেন্ডার': 'Calendar',
  'টপ ফিচার': 'Top features',
  'ট্র্যাকার': 'Tracker',
  'রোজা': 'Fasting',
  'কিবলা': 'Qibla',
  'তসবিহ': 'Tasbih',
  'আমল': 'Amol',
  'জাকাত': 'Zakat',
  'কুরআন': 'Quran',
  'হাদিস': 'Hadith',
  'শীঘ্রই': 'Soon',
  'চলছে': 'Running',
  'আদায় টিক দেওয়া নেই': 'Not marked as prayed',
  'অ্যালার্ম ও সময়': 'Alarm & times',
  'নামাজের ক্যালেন্ডার': 'Prayer calendar',
  'স্থান বাছুন': 'Choose location',
  'নামাজের ট্র্যাকার': 'Prayer tracker',
  'রোজা (সাহরি ও ইফতার)': 'Fasting (Sehri & Iftar)',
  'এই সপ্তাহ': 'This week',
  'টানা সম্পূর্ণ': 'Full-day streak',
  'আজ': 'Today',
  'পরের ধাপে আসছে': 'Coming in the next step',
  'আমার বর্তমান অবস্থান ব্যবহার করুন': 'Use my current location',
  'অবস্থান খোঁজা হচ্ছে...': 'Finding location...',
  'আগের ৭ দিনের টিক বদলানো যায়। তথ্য শুধু আপনার ফোনে থাকে।': 'You can edit the ticks of the last 7 days. Data stays only on your phone.',
  'সময়গুলো গাণিতিক হিসাবে। স্থানীয় মসজিদের সূচির সাথে ফারাক থাকলে অ্যালার্ম বাটনের "সময় মিলান" ব্যবহার করুন।':
    'Times are calculated mathematically. If they differ from your local mosque, use "Adjust times" under the Alarm button.',
  'অ্যালার্ম চালু করুন': 'Turn alarm on',
  'অ্যালার্ম বন্ধ করুন': 'Turn alarm off',
  'সময় মিলান': 'Adjust times',
  'স্থানীয় মসজিদের সূচির সাথে ফারাক থাকলে মিনিট কমান বা বাড়ান।': 'If it differs from your local mosque, add or subtract minutes.',
  'সাহরির অ্যালার্ম ফজরের': 'Sehri alarm before Fajr by',
  'মিনিট আগে': 'minutes',
  'সূর্যোদয়': 'Sunrise',
  'তারিখ': 'Date',
}

export default D
