const D: Record<string, string> = {
  'ওভারভিউ': 'Overview',
  'আয়-ব্যয়ের চার্ট ও সর্বোচ্চ দাতা': 'Income-expense charts & top donors',
  'সংগঠনের সারসংক্ষেপ': 'Organization summary',
  'মোট আয়': 'Total income',
  'মোট ব্যয়': 'Total expense',
  'বর্তমান উদ্বৃত্ত': 'Current balance',
  'সদস্য সংখ্যা': 'Members',
  'মোট প্রবৃদ্ধি': 'Total growth',
  'এই বছরে কোনো লেনদেন নেই': 'No transactions this year',
  'সর্বোচ্চ দাতা': 'Top donors',
  'মাসিক অনুদান': 'Monthly donations',
  'মোট অনুদানের': 'of total donations',
  'বার': 'times',
  'সর্বশেষ অনুদান': 'Recent donations',
  'সব দেখুন →': 'View all →',
  'কোটি': 'crore',
  'লাখ': 'lakh',

  'প্রধান': 'Main',
  'তহবিল ও কার্যক্রম': 'Funds & activities',
  'সেবা': 'Services',
  'অ্যাকাউন্ট': 'Account',
  'ব্যবস্থাপনা': 'Management',
  'এ মাসের ফি সংগ্রহ': 'This month\'s fee collection',
  'অগ্রগতি': 'Progress',

  'শুভ সকাল': 'Good morning',
  'শুভ দুপুর': 'Good afternoon',
  'শুভ বিকাল': 'Good afternoon',
  'শুভ সন্ধ্যা': 'Good evening',
  'শুভ রাত্রি': 'Good night',
  'অতিথি': 'Guest',
  'লগইন করা নেই': 'Not logged in',
  'প্রোফাইল অপশন খুঁজুন...': 'Search profile options...',
  'আপনার ছোট দানও একজন অসহায় মানুষের পাশে দাঁড়ায়।': 'Even a small donation stands beside someone in need.',
  'ডার্ক মোড': 'Dark mode',
  'নোটিশ টিকার': 'Notice ticker',
  'অ্যাকাউন্ট সেটিংস': 'Account settings',
  'শেয়ার করুন': 'Share',
  'ভাষা পরিবর্তন (বাং)': 'Change language',
  'কিছু পাওয়া যায়নি': 'Nothing found',
  'প্রোফাইল': 'Profile',

  'স্বাগতম': 'Welcome',
  'ইমেইল ঠিকানা': 'Email address',
  'পাসওয়ার্ড ভুলে গেছেন?': 'Forgot password?',
  'আগে উপরে আপনার ইমেইল লিখুন': 'Enter your email above first',
  'সদস্য নন?': 'Not a member?',
  'সদস্য হওয়ার আবেদন করুন': 'Apply for membership',
  'আগে থেকেই সদস্য?': 'Already a member?',
  'লগইন করুন': 'Log in',
}

export default D
